# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - osx
  - linux

julia:
  - 0.7
  - 1.0
  - nightly

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
# matrix:
#   allow_failures:
#   - julia: nightly

notifications:
  email: false

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Example"); Pkg.test("Example"; coverage=true)';

after_success:
  - julia -e 'using Pkg; using BinaryCommitteeMachineRSGD; Pkg.add("Coverage"); using Coverage; get(ENV,"TRAVIS_OS_NAME","")=="linux" && get(ENV,"TRAVIS_JULIA_VERSION","")=="1.0" && Codecov.submit(Codecov.process_folder())'
  - DOCUMENTER_DEBUG=true julia -e 'using Pkg; Pkg.add("Documenter"); get(ENV,"TRAVIS_OS_NAME","")=="linux" && include("docs/make.jl")'
