site_name:        BinaryCommitteeMachineRSGD.jl
repo_url:         https://github.com/carlobaldassi/BinaryCommitteeMachineRSGD.jl
site_description: Julia package BinaryCommitteeMachineRSGD.jl
site_author:      Carlo Baldassi, Alessandro Ingrosso

theme: yeti

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md

